Registers:
  AbsolutePosLow: 8
  AbsolutePosHigh: 9
  StateRunning: 1
  ModeControl: 18
  EmergencyStopDec: 78
  Reverse: 23
  InputState: 2
  PosControlPosLow16bit: 73
  PosControlPosHigh16bit: 74
  PosControlAcc: 70
  PosControlDec: 71
  PosControlSpeed: 72
  PositionAbsolute: 84